### ISSUE TITLE
aov del diseño aumentado

### ISSUE THREAD

**Issue by omarbenites** [reyzaguirre/pepa#12]
Hoy volvieron a pedirlo. 

/////
**From: Miki, Maria (CIP)** 
**Sent: Tuesday, July 4, 2017 08:03 AM**
**To: Benites, Omar (CIP) <O.Benites@cgiar.org>**
**Subject: Diseño aumentado**

**Hola Omar**
**Por favor, pudiste revisar el tema de las fuente de variación en los ANOVA del Diseño Aumentado en Hidap?**

María**
/////////

Hay que incluirlo para que lo tengan en su reporte :bookmark: .

**Comment by reyzaguirre** [comment]
La respuesta puede ser:
El análisis de varianza solo tiene sentido con fuentes de variación que son ortogonales. En el diseño aumentado solo se podría presentar un análisis de varianza para los checks, pero dado que los checks por lo general no son de interés, el análisis carece de sentido.

**Comment by cipriuhq** [comment]
Solucionado. 
Ya puedes cerrar el issue.
