### ISSUE TITLE
error hidap-spbase dataset

### ISSUE THREAD

**Issue by omarbenites** [reyzaguirre/pepa#15]
Sale un error cuando analizo un dataset de NCSU-Kinston bajo un diseño DCA en hidap-spbase. 

[kingston2016.xlsx](https://github.com/reyzaguirre/pepa/files/2079118/kingston2016.xlsx)

genotipos:  accession_name
rep: rep_number
trait: ex:  cualquiera.

![image](https://user-images.githubusercontent.com/5264796/41080952-8aef691e-6a31-11e8-91e5-9a973c625493.png)

**Comment by reyzaguirre** [comment]
Solo hay una repeticion.
